import { useEffect, useMemo, useState } from 'react';

const API = 'https://api.tvmaze.com';
const PAGE_SIZE = 24;
const plain = (value = '') => value.replace(/<[^>]*>/g, '').replace(/&amp;/g, '&');
const year = (date) => date ? new Date(date).getFullYear() : 'TBA';

function Brand({ navigate }) {
  return <button onClick={() => navigate('home')} className="font-bold tracking-[.16em] text-white"><span className="mr-1 text-xl text-coral">◉</span>CINEMORA</button>;
}

function Header({ navigate, active, hero = false }) {
  return <header className={hero ? 'relative min-h-[44rem] overflow-hidden bg-ink text-white' : 'bg-ink text-white shadow-[inset_0_-30px_65px_rgba(239,104,69,.08)]'}>
    {hero && <><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,10,22,.98),rgba(5,10,22,.7)_45%,rgba(5,10,22,.25)),url('https://static.tvmaze.com/uploads/images/original_untouched/1/4388.jpg')] bg-cover bg-center" /><div className="absolute -right-24 top-24 size-125 rounded-full border border-coral/40 shadow-[0_0_0_55px_rgba(239,104,69,.05),0_0_0_110px_rgba(239,104,69,.03),0_0_120px_rgba(239,104,69,.25)]" /><div className="absolute left-[43%] top-18 size-56 rounded-full bg-coral/10 blur-[100px]" /></>}
    <nav className="relative z-10 mx-auto flex h-21 max-w-[1440px] items-center justify-between border-b border-white/15 px-6 md:px-12">
      <Brand navigate={navigate} />
      <div className="flex items-center gap-6 text-sm"><button onClick={() => navigate('home')} className={`hidden sm:block ${active === 'home' ? 'border-b border-coral pb-1' : 'text-white/70'}`}>Home</button><button onClick={() => navigate('movies')} className={`hidden sm:block ${active === 'movies' ? 'border-b border-coral pb-1' : 'text-white/70'}`}>Discover</button><button onClick={() => navigate(active === 'home' ? 'movies' : 'home')} className="bg-white px-4 py-2.5 font-semibold text-slate-900 transition hover:bg-coral hover:text-white">{active === 'home' ? 'Browse movies' : 'Back home'}</button></div>
    </nav>
    {!hero && <div className="relative overflow-hidden border-b border-white/10 bg-[radial-gradient(circle_at_86%_20%,rgba(239,104,69,.42),transparent_17%),linear-gradient(115deg,#0a1020,#17213b)]"><div className="absolute -right-10 -top-14 size-64 rounded-full border border-coral/25 shadow-[0_0_100px_rgba(239,104,69,.23)]" /><div className="mx-auto flex max-w-[1440px] items-end justify-between px-6 py-11 md:px-12"><div><p className="font-mono text-[10px] tracking-[.18em] text-coral drop-shadow-[0_0_10px_rgba(239,104,69,.8)]">CINEMORA / DISCOVER</p><h1 className="mt-4 font-display text-4xl leading-none drop-shadow-[0_8px_30px_rgba(0,0,0,.35)] md:text-6xl">The stories worth<br /><em className="font-normal text-white/70">making time for.</em></h1></div><div className="hidden border-l border-white/15 pl-7 font-mono text-[10px] leading-5 tracking-[.12em] text-white/55 md:block">CURATED WEEKLY<br /><span className="text-coral">01 — 250 TITLES</span></div></div></div>}
    {hero && <><div className="relative z-10 mx-auto max-w-[1440px] px-6 py-28 md:px-24"><div className="max-w-xl"><p className="font-mono text-[11px] tracking-[.18em] text-coral">YOUR NEXT OBSESSION AWAITS</p><h1 className="mt-5 font-display text-6xl leading-[.92] tracking-tight md:text-8xl">Stories that<br /><em className="font-normal">stay with you.</em></h1><p className="mt-7 max-w-md leading-7 text-white/75">Find captivating series, unforgettable characters, and your next late-night watch in one beautiful collection.</p><button onClick={() => navigate('movies')} className="mt-8 bg-coral px-5 py-3.5 text-sm font-bold shadow-lg shadow-coral/20 transition hover:-translate-y-0.5 hover:bg-[#d85334]">Explore the collection <span className="ml-7">↓</span></button></div><div className="absolute right-[14%] top-28 hidden w-45 rotate-4 overflow-hidden border border-white/50 bg-ink shadow-[18px_18px_0_#ef6845,0_22px_55px_rgba(0,0,0,.45)] lg:block"><img className="h-60 w-full object-cover" src="https://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg" alt="Featured show" /><p className="p-4 font-mono text-[10px] tracking-wider">EDITOR&apos;S PICK<br /><span className="mt-2 block text-coral">★ 8.9 · DRAMA</span></p></div></div><div className="absolute bottom-6 left-6 right-6 z-10 mx-auto flex max-w-[1248px] justify-between border-t border-white/15 pt-4 font-mono text-[9px] tracking-[.14em] text-white/60 md:left-12 md:right-12"><span>CURATED FOR THE CURIOUS</span><span className="hidden sm:block">TV SHOWS · FILM · STORIES</span></div></>}
  </header>;
}

function Card({ show, onOpen }) {
  return <article className="group flex min-h-full flex-col overflow-hidden border border-black/5 bg-white shadow-[0_8px_24px_rgba(20,18,14,.06)] transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_18px_35px_rgba(20,18,14,.15)]"><div className="relative aspect-[2/2.75] overflow-hidden bg-slate-800">{show.image?.medium ? <img className="h-full w-full object-cover transition duration-500 group-hover:scale-105" src={show.image.medium} alt={`${show.name} poster`} loading="lazy" /> : <div className="grid h-full place-items-center px-5 text-center text-sm text-white/60">Image unavailable</div>}<span className="absolute right-3 top-3 bg-ink px-2 py-1 font-mono text-[10px] text-white">★ {show.rating?.average ?? 'N/A'}</span></div><div className="flex flex-1 flex-col p-4"><p className="font-mono text-[9px] tracking-[.12em] text-coral">{show.genres?.[0] || 'SERIES'} · {year(show.premiered)}</p><h3 className="mt-2 font-display text-[22px] leading-6">{show.name}</h3><p className="mt-2 line-clamp-2 text-[13px] leading-5 text-slate-500">{plain(show.summary) || 'A story waiting to be discovered.'}</p><button onClick={() => onOpen(show)} className="mt-auto pt-4 text-left text-xs font-bold underline underline-offset-5 transition hover:text-coral">See details <span className="ml-1 text-base">→</span></button></div></article>;
}

function Modal({ show, close }) {
  useEffect(() => { const key = (e) => e.key === 'Escape' && close(); document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key); }, [close]);
  return <div onMouseDown={(e) => e.target === e.currentTarget && close()} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4 backdrop-blur-sm"><section className="relative grid max-h-[92vh] w-full max-w-4xl overflow-auto bg-[#f7f3eb] shadow-2xl md:grid-cols-[38%_1fr]"><button onClick={close} className="absolute right-3 top-3 z-10 grid size-9 place-items-center rounded-full bg-white text-2xl shadow hover:bg-coral hover:text-white">×</button><div className="min-h-72 bg-slate-800">{show.image?.original && <img className="h-full w-full object-cover" src={show.image.original} alt="" />}</div><div className="p-8 md:p-12"><p className="font-mono text-[10px] tracking-[.14em] text-coral">{show.type} · {show.status}</p><h2 className="mt-3 font-display text-5xl leading-none">{show.name}</h2><p className="mt-5 font-mono text-[10px] text-slate-500">★ {show.rating?.average ?? 'N/A'} RATING <span className="mx-2">|</span> {year(show.premiered)} RELEASE <span className="mx-2">|</span> {show.runtime || '—'} MIN</p><p className="mt-7 leading-7 text-slate-600">{plain(show.summary) || 'No overview available.'}</p><div className="mt-6 flex flex-wrap gap-2">{show.genres?.map((item) => <span key={item} className="border border-stone-300 px-2.5 py-1 font-mono text-[10px]">{item}</span>)}</div></div></section></div>;
}

function Home({ navigate }) {
  const benefits = [['01', 'Thoughtfully curated', 'Great titles, all in one distraction-free place.'], ['02', 'Search instantly', 'Find any title with a quick, responsive search.'], ['03', 'Know before you watch', 'Ratings, genres and story details at a glance.']];
  return <><Header navigate={navigate} active="home" hero /><section className="grid gap-10 bg-paper px-6 py-20 md:grid-cols-[1fr_2fr_1fr] md:px-[11vw] md:py-28"><p className="font-mono text-[10px] tracking-[.15em] text-coral">A BETTER WAY TO BROWSE</p><div><h2 className="font-display text-5xl leading-none tracking-tight md:text-6xl">Find the story<br />that <em className="font-normal">moves you.</em></h2><p className="mt-6 max-w-md leading-7 text-slate-500">Search a constantly growing library, explore every detail, and spend less time looking for something worth watching.</p></div><button onClick={() => navigate('movies')} className="self-end justify-self-start border-b border-slate-900 pb-1 text-sm font-bold">Start discovering <span className="ml-3 text-lg">→</span></button></section><section className="grid bg-[#d9d4ca] px-6 md:grid-cols-3 md:px-[11vw]">{benefits.map(([num,title,copy], i) => <article key={num} className={`py-12 ${i ? 'border-t border-stone-400 md:border-l md:border-t-0 md:pl-9' : ''} md:pr-9`}><span className="font-mono text-[10px] text-coral">{num}</span><h3 className="mt-5 font-display text-2xl">{title}</h3><p className="mt-2 max-w-55 text-sm leading-6 text-slate-600">{copy}</p></article>)}</section><section className="bg-ink px-6 py-18 text-white md:px-[11vw]"><div className="mx-auto grid max-w-6xl overflow-hidden border border-white/15 md:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-85 overflow-hidden"><img src="https://static.tvmaze.com/uploads/images/original_untouched/1/4388.jpg" alt="A featured show" className="absolute inset-0 h-full w-full object-cover opacity-80" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/10 to-transparent" /><div className="absolute bottom-6 left-6 font-mono text-[10px] tracking-[.15em] text-white/70">TONIGHT&apos;S SELECTION<br /><span className="mt-2 block text-coral">★ 8.7 · CRITIC FAVORITE</span></div></div><div className="flex flex-col justify-center p-8 md:p-14"><p className="font-mono text-[10px] tracking-[.16em] text-coral">THE EDITORIAL PICK</p><h2 className="mt-5 font-display text-4xl leading-none md:text-5xl">One story can<br /><em className="font-normal">change the night.</em></h2><p className="mt-6 max-w-sm leading-7 text-white/65">Let the mood choose for you. Explore acclaimed drama, unforgettable comedy, and everything in between.</p><button onClick={() => navigate('movies')} className="mt-8 w-fit border-b border-white/70 pb-1 text-sm font-bold transition hover:border-coral hover:text-coral">Discover the collection <span className="ml-4 text-lg">→</span></button></div></div></section></>;
}

function Movies({ navigate, onOpen }) {
  const [shows, setShows] = useState([]), [query, setQuery] = useState(''), [genre, setGenre] = useState('All'), [sort, setSort] = useState('featured'), [limit, setLimit] = useState(PAGE_SIZE), [loading, setLoading] = useState(true), [error, setError] = useState('');
  useEffect(() => { const c = new AbortController(); const t = setTimeout(async () => { setLoading(true); setError(''); try { const q = query.trim(); const r = await fetch(q ? `${API}/search/shows?q=${encodeURIComponent(q)}` : `${API}/shows`, { signal: c.signal }); const data = await r.json(); setShows(q ? data.map(({ show }) => show) : data); setLimit(PAGE_SIZE); } catch (e) { if (e.name !== 'AbortError') setError('We could not reach the library. Please try again.'); } finally { if (!c.signal.aborted) setLoading(false); } }, query ? 350 : 0); return () => { clearTimeout(t); c.abort(); }; }, [query]);
  const genres = useMemo(() => ['All', ...new Set(shows.flatMap((s) => s.genres || []))].slice(0, 7), [shows]);
  const results = useMemo(() => { const list = genre === 'All' ? [...shows] : shows.filter((s) => s.genres?.includes(genre)); if (sort === 'rating') list.sort((a,b) => (b.rating?.average || 0) - (a.rating?.average || 0)); if (sort === 'newest') list.sort((a,b) => new Date(b.premiered || 0) - new Date(a.premiered || 0)); return list; }, [shows, genre, sort]);
  const visible = results.slice(0, limit);
  return <><Header navigate={navigate} active="movies" /><main className="mx-auto max-w-[1280px] bg-[radial-gradient(circle_at_100%_0,rgba(239,104,69,.13),transparent_22%)] px-6 py-16 md:px-20"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[10px] tracking-[.15em] text-coral">THE LIBRARY</p><h1 className="mt-4 font-display text-5xl tracking-tight md:text-6xl">Find your <em className="font-normal">next favorite.</em></h1></div><p className="max-w-64 leading-6 text-slate-500">Browse shows from around the world, then make the night yours.</p></section><div className="mt-11 flex border-b border-stone-400 pb-3 focus-within:border-slate-900"><span className="mr-3 text-2xl text-slate-500">⌕</span><input className="w-full bg-transparent text-lg outline-none placeholder:text-stone-400" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search for a title..." />{query && <button onClick={() => setQuery('')} className="text-2xl text-slate-500">×</button>}</div><div className="flex flex-col justify-between gap-4 border-b border-stone-300 py-5 md:flex-row md:items-center"><div className="flex max-w-full gap-2 overflow-auto">{genres.map((item) => <button key={item} onClick={() => setGenre(item)} className={`whitespace-nowrap rounded-full border px-3 py-1.5 text-xs ${genre === item ? 'border-ink bg-ink text-white' : 'border-stone-300 text-slate-600'}`}>{item}</button>)}</div><select className="bg-transparent font-mono text-[11px] outline-none" value={sort} onChange={(e) => setSort(e.target.value)}><option value="featured">SORT: FEATURED</option><option value="rating">SORT: TOP RATED</option><option value="newest">SORT: NEWEST</option></select></div><div className="flex justify-between py-7 font-mono text-[11px] text-slate-600"><span>{query ? `RESULTS FOR “${query}”` : 'POPULAR PICKS'}</span><span>{loading ? 'LOADING…' : `${results.length} TITLES`}</span></div>{loading ? <div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{Array.from({length:8},(_,i) => <div key={i} className="h-100 animate-pulse bg-stone-200" />)}</div> : error ? <div className="py-20 text-center">{error}</div> : <div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{visible.map((show) => <Card key={show.id} show={show} onOpen={onOpen} />)}</div>}{visible.length < results.length && <div className="pt-12 text-center"><button onClick={() => setLimit((n) => n + PAGE_SIZE)} className="bg-ink px-5 py-3 text-sm font-bold text-white hover:bg-coral">Load more titles <span className="ml-6">↓</span></button></div>}</main></>;
}

function Footer({ navigate }) { return <footer className="relative overflow-hidden bg-[#080d19] text-white"><div className="absolute -bottom-25 right-0 font-display text-[30rem] leading-none text-white/[.025]">C</div><div className="relative mx-auto grid max-w-[1280px] gap-12 px-6 py-18 md:grid-cols-[1.4fr_1fr_.8fr] md:px-20"><div><Brand navigate={navigate}/><p className="mt-5 max-w-70 text-sm leading-6 text-slate-400">Thoughtful stories for curious people. Find the next title worth staying up for.</p><a href="mailto:hello@cinemora.example" className="mt-6 inline-block border-b border-coral pb-1 text-sm">hello@cinemora.example ↗</a></div><div className="grid grid-cols-2 gap-8 text-sm text-slate-300"><div><p className="font-mono text-[10px] tracking-[.16em] text-coral">EXPLORE</p><div className="mt-5 flex flex-col gap-3"><button onClick={() => navigate('home')} className="text-left">Home</button><button onClick={() => navigate('movies')} className="text-left">Discover titles</button></div></div><div><p className="font-mono text-[10px] tracking-[.16em] text-coral">FOLLOW</p><div className="mt-5 flex flex-col gap-3"><a href="https://www.tvmaze.com" target="_blank" rel="noreferrer">TVMaze</a><a href="https://github.com" target="_blank" rel="noreferrer">GitHub</a></div></div></div><blockquote className="border-l border-white/20 pl-7 font-display text-2xl leading-7">One good story can change an ordinary evening.</blockquote></div><div className="relative mx-auto flex max-w-[1280px] flex-col gap-3 border-t border-white/10 px-6 py-5 font-mono text-[9px] tracking-wider text-slate-500 md:flex-row md:justify-between md:px-20"><span>© 2026 CINEMORA. ALL RIGHTS RESERVED.</span><button onClick={() => window.scrollTo({top:0,behavior:'smooth'})} className="w-fit border-b border-slate-600 pb-1 text-slate-200">BACK TO TOP ↑</button></div></footer>; }

export default function App() { const [page, setPage] = useState(() => window.location.hash === '#movies' ? 'movies' : 'home'); const [selected, setSelected] = useState(null); const navigate = (to) => { window.location.hash = to === 'movies' ? 'movies' : 'home'; setPage(to); window.scrollTo({top:0,behavior:'smooth'}); }; return <div className="min-h-screen selection:bg-coral selection:text-white">{page === 'home' ? <Home navigate={navigate} /> : <Movies navigate={navigate} onOpen={setSelected} />}<Footer navigate={navigate}/>{selected && <Modal show={selected} close={() => setSelected(null)} />}</div>; }
