import { useEffect, useMemo, useState } from 'react';

const API = 'https://api.tvmaze.com';
const PAGE_SIZE = 24;
const cleanText = (value = '') => value.replace(/<[^>]*>/g, '').replace(/&amp;/g, '&').trim();
const releaseYear = (date) => date ? new Date(date).getFullYear() : 'TBA';
const score = (show) => show.rating?.average ?? 0;

function MovieCard({ show, onDetails }) {
  return <article className="movie-card"><div className="poster-wrap">{show.image?.medium ? <img src={show.image.medium} alt={`${show.name} poster`} loading="lazy" /> : <div className="no-poster">Image unavailable</div>}<span className="rating">&#9733; {show.rating?.average ?? 'N/A'}</span></div><div className="card-copy"><p className="eyebrow">{show.genres?.[0] || show.type || 'Series'} <b>&middot;</b> {releaseYear(show.premiered)}</p><h3>{show.name}</h3><p className="card-summary">{cleanText(show.summary) || 'A story waiting to be discovered.'}</p><button className="details-button" onClick={() => onDetails(show)}>See details <span aria-hidden="true">&rarr;</span></button></div></article>;
}

function SkeletonCard() { return <div className="skeleton-card"><div /><span /><span /><i /></div>; }

function DetailsModal({ show, onClose }) {
  useEffect(() => { const keydown = (event) => event.key === 'Escape' && onClose(); document.addEventListener('keydown', keydown); document.body.classList.add('modal-open'); return () => { document.removeEventListener('keydown', keydown); document.body.classList.remove('modal-open'); }; }, [onClose]);
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="close" onClick={onClose} aria-label="Close details">&times;</button><div className="modal-image">{show.image?.original ? <img src={show.image.original} alt={`${show.name} artwork`} /> : <div className="no-poster">Image unavailable</div>}</div><div className="modal-copy"><p className="eyebrow">{show.type || 'SHOW'} <b>&middot;</b> {show.status || 'Unknown status'}</p><h2 id="modal-title">{show.name}</h2><div className="facts"><span>&#9733; {show.rating?.average ?? 'N/A'} rating</span><span>{releaseYear(show.premiered)} release</span><span>{show.runtime ? `${show.runtime} min` : 'Runtime TBA'}</span></div><p>{cleanText(show.summary) || 'No overview is available for this title yet.'}</p>{show.genres?.length > 0 && <div className="genres">{show.genres.map((genre) => <span key={genre}>{genre}</span>)}</div>}{show.network?.name && <p className="network">Available on <strong>{show.webChannel?.name || show.network.name}</strong></p>}{show.officialSite && <a className="site-link" href={show.officialSite} target="_blank" rel="noreferrer">Official website <span>&nearr;</span></a>}</div></section></div>;
}

function Home({ navigate }) {
  return <><header className="hero" id="home"><nav className="top-nav"><button className="brand" onClick={() => navigate('home')}><i>&#9673;</i> CINEMORA</button><div className="nav-links"><button className="text-nav active" onClick={() => navigate('home')}>Home</button><button className="text-nav" onClick={() => navigate('movies')}>Discover</button><button className="nav-cta" onClick={() => navigate('movies')}>Browse movies</button></div></nav><div className="hero-content"><p className="kicker">YOUR NEXT OBSESSION AWAITS</p><h1>Stories that<br /><em>stay with you.</em></h1><p className="hero-text">Find captivating series, unforgettable characters, and your next late-night watch in one beautiful collection.</p><button className="primary" onClick={() => navigate('movies')}>Explore the collection <span>&darr;</span></button></div><div className="hero-credit"><span>CURATED FOR THE CURIOUS</span><span>TV SHOWS &middot; FILM &middot; STORIES</span></div></header><section className="home-intro"><p className="kicker">A BETTER WAY TO BROWSE</p><div><h2>Find the story<br />that <em>moves you.</em></h2><p>Search a constantly growing library, explore every detail, and save time finding something worth watching.</p></div><button className="underlined-link" onClick={() => navigate('movies')}>Start discovering <span>&rarr;</span></button></section><section className="benefits"><article><span>01</span><h3>Thoughtfully curated</h3><p>Great titles, all in one distraction-free place.</p></article><article><span>02</span><h3>Search instantly</h3><p>Find any title with a quick, responsive search.</p></article><article><span>03</span><h3>Know before you watch</h3><p>Ratings, genres and story details at a glance.</p></article></section></>;
}

function Footer({ navigate }) {
  return <footer className="site-footer">
    <div className="footer-main">
      <div className="footer-intro"><button className="brand" onClick={() => navigate('home')}><i>&#9673;</i> CINEMORA</button><p>Thoughtful stories for curious people. Find the next title worth staying up for.</p><a className="footer-mail" href="mailto:hello@cinemora.example">hello@cinemora.example <span>&nearr;</span></a></div>
      <div className="footer-links"><div><p className="footer-label">EXPLORE</p><button onClick={() => navigate('home')}>Home</button><button onClick={() => navigate('movies')}>Discover titles</button><button onClick={() => navigate('movies')}>Top rated</button></div><div><p className="footer-label">FOLLOW</p><a href="https://www.tvmaze.com" target="_blank" rel="noreferrer">TVMaze</a><a href="https://github.com" target="_blank" rel="noreferrer">GitHub</a><a href="mailto:hello@cinemora.example">Contact</a></div></div>
      <div className="footer-quote"><span>&ldquo;</span><p>One good story can change an ordinary evening.</p></div>
    </div>
    <div className="footer-bottom"><p>&copy; 2026 CINEMORA. ALL RIGHTS RESERVED.</p><p>BUILT FOR MOVIE LOVERS <b>&#9679;</b></p><button onClick={() => { window.scrollTo({ top: 0, behavior: 'smooth' }); }}>BACK TO TOP &uarr;</button></div>
  </footer>;
}

function Movies({ navigate, onDetails }) {
  const [shows, setShows] = useState([]); const [query, setQuery] = useState(''); const [genre, setGenre] = useState('All'); const [sort, setSort] = useState('featured'); const [limit, setLimit] = useState(PAGE_SIZE); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(async () => { setLoading(true); setError(''); setLimit(PAGE_SIZE); try { const trimmed = query.trim(); const response = await fetch(trimmed ? `${API}/search/shows?q=${encodeURIComponent(trimmed)}` : `${API}/shows`, { signal: controller.signal }); if (!response.ok) throw new Error('Request failed'); const data = await response.json(); setShows(trimmed ? data.map(({ show }) => show) : data); } catch (err) { if (err.name !== 'AbortError') setError('We could not reach the library. Check your connection and try again.'); } finally { if (!controller.signal.aborted) setLoading(false); } }, query ? 350 : 0); return () => { clearTimeout(timer); controller.abort(); }; }, [query]);
  const genres = useMemo(() => ['All', ...new Set(shows.flatMap((show) => show.genres || []))].slice(0, 7), [shows]);
  const filteredShows = useMemo(() => { const list = genre === 'All' ? [...shows] : shows.filter((show) => show.genres?.includes(genre)); if (sort === 'rating') list.sort((a, b) => score(b) - score(a)); if (sort === 'newest') list.sort((a, b) => new Date(b.premiered || 0) - new Date(a.premiered || 0)); return list; }, [shows, genre, sort]);
  const visibleShows = filteredShows.slice(0, limit);
  return <><header className="listing-banner"><nav className="top-nav listing-nav"><button className="brand" onClick={() => navigate('home')}><i>&#9673;</i> CINEMORA</button><div className="nav-links"><button className="text-nav" onClick={() => navigate('home')}>Home</button><button className="text-nav active">Discover</button><button className="nav-cta" onClick={() => navigate('home')}>Back home</button></div></nav></header><main className="movies-page"><section className="discover-head"><div><p className="kicker">THE LIBRARY</p><h1>Find your <em>next favorite.</em></h1></div><p>Browse shows from around the world, then make the night yours.</p></section><div className="search-wrap"><span aria-hidden="true">&#8981;</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search for a title..." aria-label="Search for a movie" />{query && <button onClick={() => setQuery('')} aria-label="Clear search">&times;</button>}</div><section className="toolbar"><div className="chips" aria-label="Filter by genre">{genres.map((item) => <button key={item} className={genre === item ? 'selected' : ''} onClick={() => { setGenre(item); setLimit(PAGE_SIZE); }}>{item}</button>)}</div><label className="sort-label">Sort <select value={sort} onChange={(event) => setSort(event.target.value)}><option value="featured">Featured</option><option value="rating">Top rated</option><option value="newest">Newest</option></select></label></section><section className="results" aria-live="polite"><p>{query ? `Results for “${query}”` : 'Popular picks'}</p><span>{loading ? 'Loading…' : `${filteredShows.length} titles`}</span></section>{loading && <section className="movie-grid">{Array.from({ length: 8 }, (_, index) => <SkeletonCard key={index} />)}</section>}{error && <div className="status error"><p>{error}</p><button className="retry" onClick={() => setQuery((value) => `${value} `)}>Try again</button></div>}{!loading && !error && filteredShows.length === 0 && <div className="status">No titles match this search. Try another title or genre.</div>}{!loading && !error && <section className="movie-grid">{visibleShows.map((show) => <MovieCard key={show.id} show={show} onDetails={onDetails} />)}</section>}{!loading && visibleShows.length < filteredShows.length && <div className="load-more"><button className="primary dark" onClick={() => setLimit((current) => current + PAGE_SIZE)}>Load more titles <span>&darr;</span></button></div>}</main></>;
}

export default function App() {
  const [page, setPage] = useState(() => window.location.hash === '#movies' ? 'movies' : 'home'); const [selected, setSelected] = useState(null);
  const navigate = (destination) => { window.location.hash = destination === 'movies' ? 'movies' : 'home'; setPage(destination); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  useEffect(() => { const hashChange = () => setPage(window.location.hash === '#movies' ? 'movies' : 'home'); window.addEventListener('hashchange', hashChange); return () => window.removeEventListener('hashchange', hashChange); }, []);
  return <><div className="app-shell">{page === 'home' ? <Home navigate={navigate} /> : <Movies navigate={navigate} onDetails={setSelected} />}</div><Footer navigate={navigate} />{selected && <DetailsModal show={selected} onClose={() => setSelected(null)} />}</>;
}
